/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Database;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Fransiko Sihombing
 */
public class Form_mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Form_mahasiswa
     */
    
    final DefaultTableModel mdl;
    Connection c;
    ResultSet res;
    Statement stet;
    String nama,kelas;
    public Form_mahasiswa(String nama) {
        initComponents();
        this.nama = nama;
        
        vNama.setText(nama);
        
        
        mdl = new DefaultTableModel();
        tb_mahasiswa.setModel(mdl);
        mdl.addColumn("NIM");
        mdl.addColumn("NAMA");
        mdl.addColumn("JENIS KELAMIN");
        mdl.addColumn("KELAS");
        mdl.addColumn("ALAMAT");
        tampil_data();
    }
    
    public void tampil_data(){
        mdl.getDataVector().removeAllElements();
        mdl.fireTableDataChanged();
        try{
            c = koneksi_db.getKoneksi();
            try(Statement s= c.createStatement()){
                String sql="select * from tbl_mahasiswa";
                res= s.executeQuery(sql);
                while(res.next()){
                    Object[] x = new Object[5];
                    x[0]=res.getString("nim");
                    x[1]=res.getString("nama");
                    x[2]=res.getString("jenkel");
                    x[3]=res.getString("kelas");
                    x[4]=res.getString("alamat");
                    mdl.addRow(x);
                }
                res.close();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }
    
    public void cari(){
        try{
            stet = koneksi_db.getKoneksi().createStatement();
            res = stet.executeQuery("select * from tbl_mahasiswa where nim like '%"+txtCari.getText()+"%' ");            
            mdl.getDataVector().removeAllElements();
                while(res.next()){
                    Object[] x = new Object[5];
                    x[0]=res.getString("nim");
                    x[1]=res.getString("nama");
                    x[2]=res.getString("jenkel");
                    x[3]=res.getString("kelas");
                    x[4]=res.getString("alamat");
                    mdl.addRow(x);
                }            
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, "Terjadi Error...!","Pemberitahuan",JOptionPane.ERROR_MESSAGE);
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vNama = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_mahasiswa = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vNama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vNama.setText("Nama");

        tb_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_mahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_mahasiswa);

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCariKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Selamat Datang , ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vNama)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vNama)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyTyped
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txtCariKeyTyped

    private void tb_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_mahasiswaMouseClicked
        // TODO add your handling code here:
        
        int baris = tb_mahasiswa.rowAtPoint(evt.getPoint());
        String nim1 = tb_mahasiswa.getValueAt(baris, 0).toString();
        String nama1 = tb_mahasiswa.getValueAt(baris, 1).toString();
        String jenkell = tb_mahasiswa.getValueAt(baris, 2).toString();
        String kelas1 = tb_mahasiswa.getValueAt(baris, 3).toString();
        String alamat1 = tb_mahasiswa.getValueAt(baris, 4).toString();
        
        
        int selectedOption =  JOptionPane.showConfirmDialog(null, "Ingin Menampilan data dengan Nim : "+nim1+"?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION){
            
           new Tambah(nim1,nama1,alamat1,jenkell,kelas1).setVisible(true);
           this.dispose();   
        }
        
    }//GEN-LAST:event_tb_mahasiswaMouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_mahasiswa("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_mahasiswa;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel vNama;
    // End of variables declaration//GEN-END:variables
}
